# Form implementation generated from reading ui file 'character.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MenuWindow(object):
    def setupUi(self, MenuWindow):
        MenuWindow.setObjectName("MenuWindow")
        MenuWindow.resize(400, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MenuWindow.sizePolicy().hasHeightForWidth())
        MenuWindow.setSizePolicy(sizePolicy)
        MenuWindow.setMinimumSize(QtCore.QSize(400, 500))
        MenuWindow.setMaximumSize(QtCore.QSize(400, 500))
        palette = QtGui.QPalette()
        MenuWindow.setPalette(palette)
        MenuWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        MenuWindow.setAutoFillBackground(False)
        MenuWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MenuWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(400, 500))
        self.centralwidget.setMaximumSize(QtCore.QSize(400, 500))
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("QWidget {\n"
"                    background-color: #2b2b2b;\n"
"                }\n"
"                QPushButton {\n"
"                    color: white;\n"
"                }")
        self.centralwidget.setObjectName("centralwidget")
        self.black_BTN = QtWidgets.QPushButton(parent=self.centralwidget)
        self.black_BTN.setGeometry(QtCore.QRect(40, 240, 56, 17))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        self.black_BTN.setFont(font)
        self.black_BTN.setObjectName("black_BTN")
        self.white_BTN = QtWidgets.QPushButton(parent=self.centralwidget)
        self.white_BTN.setGeometry(QtCore.QRect(180, 240, 56, 17))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        self.white_BTN.setFont(font)
        self.white_BTN.setObjectName("white_BTN")
        self.din_BNT = QtWidgets.QPushButton(parent=self.centralwidget)
        self.din_BNT.setGeometry(QtCore.QRect(300, 240, 56, 17))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Book")
        self.din_BNT.setFont(font)
        self.din_BNT.setObjectName("din_BNT")
        self.black_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.black_label.setGeometry(QtCore.QRect(20, 120, 101, 101))
        self.black_label.setStyleSheet("")
        self.black_label.setText("")
        self.black_label.setPixmap(QtGui.QPixmap(":/black_cat_pref/black_cat.jpg"))
        self.black_label.setScaledContents(True)
        self.black_label.setObjectName("black_label")
        self.white_label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.white_label_2.setGeometry(QtCore.QRect(150, 120, 101, 101))
        self.white_label_2.setText("")
        self.white_label_2.setPixmap(QtGui.QPixmap(":/white_cat_pref/white_cat.jpg"))
        self.white_label_2.setScaledContents(True)
        self.white_label_2.setObjectName("white_label_2")
        self.din_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.din_label.setGeometry(QtCore.QRect(280, 120, 101, 101))
        self.din_label.setText("")
        self.din_label.setPixmap(QtGui.QPixmap(":/dinozarv_pref/dinozavr.jpg"))
        self.din_label.setScaledContents(True)
        self.din_label.setObjectName("din_label")
        self.choose_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.choose_label.setGeometry(QtCore.QRect(40, 30, 311, 55))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Demi")
        font.setPointSize(18)
        self.choose_label.setFont(font)
        self.choose_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.choose_label.setAutoFillBackground(False)
        self.choose_label.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    text-align: center;\n"
"}")
        self.choose_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.choose_label.setScaledContents(True)
        self.choose_label.setWordWrap(False)
        self.choose_label.setIndent(0)
        self.choose_label.setObjectName("choose_label")
        MenuWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MenuWindow)
        QtCore.QMetaObject.connectSlotsByName(MenuWindow)

    def retranslateUi(self, MenuWindow):
        _translate = QtCore.QCoreApplication.translate
        MenuWindow.setWindowTitle(_translate("MenuWindow", "MyTama"))
        self.black_BTN.setText(_translate("MenuWindow", "Choose"))
        self.white_BTN.setText(_translate("MenuWindow", "Choose"))
        self.din_BNT.setText(_translate("MenuWindow", "Choose"))
        self.choose_label.setText(_translate("MenuWindow", "<html><head/><body><p align=\"center\">Выберите своего тамагочи:</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MenuWindow = QtWidgets.QMainWindow()
    ui = Ui_MenuWindow()
    ui.setupUi(MenuWindow)
    MenuWindow.show()
    sys.exit(app.exec())
